#pragma once
//console positions
#define SCREEN_WIDTH_TO_CONSOLE (SCREEN_WIDTH-150)
#define SHIP_SHIELD_X_POS (SCREEN_WIDTH_TO_CONSOLE + 68)
#define SHIP_ENGINE_X_POS (SCREEN_WIDTH_TO_CONSOLE + 78)
#define SHIP_Y_POS 122
#define L_TURRET_RATE_X_POS (SCREEN_WIDTH_TO_CONSOLE + 18)
#define L_TURRET_POWER_X_POS (SCREEN_WIDTH_TO_CONSOLE + 28)
#define R_TURRET_RATE_X_POS (SCREEN_WIDTH_TO_CONSOLE + 118)
#define R_TURRET_POWER_X_POS (SCREEN_WIDTH_TO_CONSOLE + 128)
#define TURRET_Y_POS 80
#define L_MISSLE_RATE_X_POS (SCREEN_WIDTH_TO_CONSOLE + 48)
#define L_MISSLE_POWER_X_POS (SCREEN_WIDTH_TO_CONSOLE + 58)
#define R_MISSLE_RATE_X_POS (SCREEN_WIDTH_TO_CONSOLE + 88)
#define R_MISSLE_POWER_X_POS (SCREEN_WIDTH_TO_CONSOLE + 98)
#define MISSLE_Y_POS 83
#define BLASTER_RATE_X_POS (SCREEN_WIDTH_TO_CONSOLE + 69)
#define BLASTER_POWER_X_POS (SCREEN_WIDTH_TO_CONSOLE + 79)
#define BLASTER_Y_POS 52
#define BAR_WIDTH 4
#define BAR_HEIGHT 4
#define ARMOR_X_POS (SCREEN_WIDTH_TO_CONSOLE + 90)
#define ARMOR_Y_POS 565
#define SHIELDS_X_POS (SCREEN_WIDTH_TO_CONSOLE + 17)
#define SHIELDS_Y_POS 565
#define ARMOR_BAR_WIDTH 45
#define ARMOR_BAR_HEIGHT 1
#define SHIELDS_BAR_WIDTH 45
#define SHIELDS_BAR_HEIGHT 1
//shipcustimization positions
#define C_SHIP_SHIELD_X_POS (230)
#define C_SHIP_ENGINE_X_POS (265)
#define C_SHIP_Y_POS (258)
#define C_L_TURRET_RATE_X_POS (111)
#define C_L_TURRET_POWER_X_POS (145)
#define C_R_TURRET_RATE_X_POS (352)
#define C_R_TURRET_POWER_X_POS (387)
#define C_TURRET_Y_POS (162)
#define C_L_MISSLE_RATE_X_POS (188)
#define C_L_MISSLE_POWER_X_POS (223)
#define C_R_MISSLE_RATE_X_POS (276)
#define C_R_MISSLE_POWER_X_POS (311)
#define C_MISSLE_Y_POS (171)
#define C_BLASTER_RATE_X_POS (230)
#define C_BLASTER_POWER_X_POS (265)
#define C_BLASTER_Y_POS (102)
#define C_BAR_WIDTH 14
#define C_BAR_HEIGHT 10
